import numpy as np
import matplotlib.pyplot as plt
import scipy.io
import scipy.optimize
from sklearn import svm

DATA_PATH_1 = "data/data1.mat"
DATA_PATH_2 = "data/data2.mat"
DATA_PATH_3 = "data/data3.mat"


def read_data(path, usecols=(0, 1)):
    """
    x is a matrix with m rows and n columns
    y is a matrix with m rows and 1 column
    three input sets: training, validation and test 
    """

    raw_data = scipy.io.loadmat(path)
    x, y = raw_data["X"], raw_data["y"]
    return x, y


def train_svm(x, y, **params):
    svm_function = svm.SVC(**params)
    return svm_function.fit(x, y.flatten())


def gaussian_kernel(x1, x2, sigma):
    sigma_squared = np.power(sigma, 2)
    return np.exp(-(x1 - x2).T.dot(x1 - x2) / (2 * sigma_squared))


def plot_data(data, title="scatter plot of training data 1"):
    pos, neg = data
    plt.figure(figsize=(10, 6))
    plt.scatter(pos[:, 0], pos[:, 1], marker="+", c="k", s=150, label="Positive Sample")
    plt.scatter(neg[:, 0], neg[:, 1], marker="o", c="y", s=100, label="Negative Sample")
    plt.xlabel("Column 1 Variable")
    plt.ylabel("Column 2 Variable")
    plt.legend()
    plt.title(title)
    plt.savefig(title.replace(" ", "_").lower())


def plot_boundary(data):
    """
    used to plot the decision boundary generated by the SVM algorithm. 
    It uses a grid of points made up of x vals and y vals. 
    Each point in the grid is assigned a boolean value (true or false) 
    indicating not whether a desicion boundary exists there.
    """
    clf, x_min, x_max = data
    w = clf.coef_[0]
    a = -w[0] / w[1]

    xp = np.array(np.linspace(x_min, x_max, 100))
    yp = a * xp - (clf.intercept_[0]) / w[1]
    plt.plot(xp, yp, "-k")


def plot_boundary_gaussian(data, n=200):
    """
    used to plot the decision boundary generated by the SVM algorithm. 
    It uses a grid of points made up of x vals and y vals. 
    Each point in the grid is assigned a boolean value (true or false) 
    indicating not whether a desicion boundary exists there.
    """
    clf, x_min, x_max, y_min, y_max = data

    x_range = np.array(np.linspace(x_min, x_max, n))
    y_range = np.array(np.linspace(y_min, y_max, n))
    u, v = np.meshgrid(x_range, y_range)
    grid = np.array(list(zip(u.flatten(), v.flatten())))

    prediction_grid = clf.predict(grid).reshape((n, n))
    plt.contour(x_range, y_range, prediction_grid, cmap=plt.cm.coolwarm, extend="both")


def part_1():
    x, y = read_data(DATA_PATH_1)
    pos = np.array([x[i] for i in range(x.shape[0]) if y[i] == 1])
    neg = np.array([x[i] for i in range(x.shape[0]) if y[i] == 0])
    plot_data((pos, neg))

    for c_value in (1, 100):
        title = f"Decision boundary with C={c_value}"
        plot_data((pos, neg), title)
        plot_boundary((train_svm(x, y, C=c_value, kernel="linear"), 0, 4.5))


def part_2():
    x, y = read_data(DATA_PATH_2)
    pos = np.array([x[i] for i in range(x.shape[0]) if y[i] == 1])
    neg = np.array([x[i] for i in range(x.shape[0]) if y[i] == 0])
    plot_data((pos, neg), title="scatter plot of training data 2")

    c_value = 1
    sigma = 0.1
    title = f"Decision boundary with C={c_value}"
    plot_data((pos, neg), title)
    plot_boundary_gaussian(
        (
            train_svm(x, y, C=c_value, kernel="rbf", gamma=np.power(sigma, -2)),
            0,
            1,
            0.4,
            1,
        )
    )


def part_3():
    x, y = read_data(DATA_PATH_3)
    pos = np.array([x[i] for i in range(x.shape[0]) if y[i] == 1])
    neg = np.array([x[i] for i in range(x.shape[0]) if y[i] == 0])
    plot_data((pos, neg), title="scatter plot of training data 3")

    c_value = 2
    sigma = 0.1
    title = f"Decision boundary with C={c_value}"
    plot_data((pos, neg), title)
    plot_boundary_gaussian(
        (
            train_svm(x, y, C=c_value, kernel="rbf", gamma=np.power(sigma, -2)),
            -0.5,
            0.3,
            -0.8,
            0.6,
        )
    )


def main():
    plt.style.use("seaborn")
    part_1()
    part_2()
    part_3()
    plt.show()


if __name__ == "__main__":
    main()
