import numpy as np
import matplotlib.pyplot as plt
import scipy.io
import scipy.optimize
from sklearn import svm
from nltk.stem import PorterStemmer
import re
import pandas as pd

DATA_PATH_1 = "data/data1.mat"
DATA_PATH_2 = "data/data2.mat"
DATA_PATH_3 = "data/data3.mat"
DATA_PATH_4 = "data/emailSample1.txt"
DATA_PATH_5 = "data/vocab.txt"
DATA_PATH_6 = "data/spamTrain.mat"
DATA_PATH_7 = "data/spamTest.mat"


def read_data(path):
    """
    x is a matrix with m rows and n columns
    y is a matrix with m rows and 1 column
    """

    raw_data = scipy.io.loadmat(path)
    x, y = raw_data["X"], raw_data["y"]
    return x, y


def read_test_data(path):
    """
    x is a matrix with m rows and n columns
    y is a matrix with m rows and 1 column
    """

    raw_data = scipy.io.loadmat(path)
    x, y = raw_data["Xtest"], raw_data["ytest"]
    return x, y


def train_svm(x, y, **params):
    svm_function = svm.SVC(**params)
    return svm_function.fit(x, y.flatten())


def gaussian_kernel(x1, x2, sigma):
    sigma_squared = np.power(sigma, 2)
    return np.exp(-(x1 - x2).T.dot(x1 - x2) / (2 * sigma_squared))


def plot_data(data, title="scatter plot of training data 1"):
    pos, neg = data
    plt.figure(figsize=(10, 6))
    plt.scatter(pos[:, 0], pos[:, 1], marker="+", c="k", s=150, label="Positive Sample")
    plt.scatter(neg[:, 0], neg[:, 1], marker="o", c="y", s=100, label="Negative Sample")
    plt.xlabel("Column 1 Variable")
    plt.ylabel("Column 2 Variable")
    plt.legend()
    plt.title(title)
    plt.savefig(title.replace(" ", "_").lower())


def plot_boundary(data):
    """
    used to plot the decision boundary generated by the SVM algorithm. 
    It uses a grid of points made up of x vals and y vals. 
    Each point in the grid is assigned a boolean value (true or false) 
    indicating not whether a desicion boundary exists there.
    """
    clf, x_min, x_max = data
    w = clf.coef_[0]
    a = -w[0] / w[1]

    xp = np.array(np.linspace(x_min, x_max, 100))
    yp = a * xp - (clf.intercept_[0]) / w[1]
    plt.plot(xp, yp, "-k")


def plot_boundary_gaussian(data, n=200):
    """
    used to plot the decision boundary generated by the SVM algorithm. 
    It uses a grid of points made up of x vals and y vals. 
    Each point in the grid is assigned a boolean value (true or false) 
    indicating not whether a desicion boundary exists there.
    """
    clf, x_min, x_max, y_min, y_max = data

    x_range = np.array(np.linspace(x_min, x_max, n))
    y_range = np.array(np.linspace(y_min, y_max, n))
    u, v = np.meshgrid(x_range, y_range)
    grid = np.array(list(zip(u.flatten(), v.flatten())))

    prediction_grid = clf.predict(grid).reshape((n, n))
    plt.contour(x_range, y_range, prediction_grid, cmap=plt.cm.coolwarm, extend="both")


def read_tokens(path, vocabulary):
    with open(path, "r") as email:
        return process_email(email.read(), vocabulary)

    return list()


def read_vocabulary(path):
    with open(path, "r") as vocab:
        return [line[:-1].split("\t")[-1] for line in vocab.readlines()]

    return list()


def process_email(content, vocabulary):
    return tokenize_email(pre_processing(content), vocabulary)


def pre_processing(content):
    content = content.lower()

    def replace(old, new):
        return re.sub(old, new, content)

    # strip html tags
    content = replace("<[^<>]+>", " ")

    # replace digits with a word 'number'
    content = replace("[0-9]+", "number")

    # replace dollar signs with a word 'dollar'
    content = replace("[$]+", "dollar")

    # strings starting with http are replaced with _http
    content = replace("(http|https)://[^\s]*", "httpaddr")

    # strings containg @ sign are replaced with _addr
    content = replace("[^\s]+@[^\s]+", "contentaddr")

    return content


def tokenize_email(content, vocabulary):
    tokens = []
    words = re.split(
        r"\s|\@|\$|\/|\#|\.|\-|\:|\&|\*|\+|\=|\[|\]|\?|\!|\(|\)|\{|\}|\,|\'|\'|\"|\>|\_|\<|\;|\%",
        content,
    )

    stemmer = PorterStemmer()

    for word in words:
        # Remove nonalphanumeric characters
        alphanumeric = re.compile(r"[^a-zA-Z0-9]")
        word = alphanumeric.sub("", word)

        # Stem the word
        word = stemmer.stem(word)

        # Get index if it exists
        if word in vocabulary:
            tokens.append(vocabulary.index(word))

    return tokens


def extract_features(tokens, num_words):
    features = np.zeros(num_words)
    features[tokens] = 1
    return features


def part_1():
    x, y = read_data(DATA_PATH_1)
    pos = np.array([x[i] for i in range(x.shape[0]) if y[i] == 1])
    neg = np.array([x[i] for i in range(x.shape[0]) if y[i] == 0])
    plot_data((pos, neg))

    for c_value in (1, 100):
        title = f"Decision boundary with C={c_value}"
        plot_data((pos, neg), title)
        plot_boundary((train_svm(x, y, C=c_value, kernel="linear"), 0, 4.5))


def part_2():
    x, y = read_data(DATA_PATH_2)
    pos = np.array([x[i] for i in range(x.shape[0]) if y[i] == 1])
    neg = np.array([x[i] for i in range(x.shape[0]) if y[i] == 0])
    plot_data((pos, neg), title="scatter plot of training data 2")

    c_value = 1
    sigma = 0.1
    title = f"Decision boundary with C={c_value}"
    plot_data((pos, neg), title)
    plot_boundary_gaussian(
        (
            train_svm(x, y, C=c_value, kernel="rbf", gamma=np.power(sigma, -2)),
            0,
            1,
            0.4,
            1,
        )
    )


def part_3():
    x, y = read_data(DATA_PATH_3)
    pos = np.array([x[i] for i in range(x.shape[0]) if y[i] == 1])
    neg = np.array([x[i] for i in range(x.shape[0]) if y[i] == 0])
    plot_data((pos, neg), title="scatter plot of training data 3")

    c_value = 2
    sigma = 0.1
    title = f"Decision boundary with C={c_value}"
    plot_data((pos, neg), title)
    plot_boundary_gaussian(
        (
            train_svm(x, y, C=c_value, kernel="rbf", gamma=np.power(sigma, -2)),
            -0.5,
            0.3,
            -0.8,
            0.6,
        )
    )


def part_4():
    vocabulary = read_vocabulary(DATA_PATH_5)
    tokens = read_tokens(DATA_PATH_4, vocabulary)
    feature_vector_len = len(vocabulary)
    features = extract_features(tokens, feature_vector_len)
    non_zero_count = np.count_nonzero(features)

    print(f"Length of feature vector is {feature_vector_len}")
    print(f"Number of non-zero entries is {non_zero_count}")

    x, y = read_data(DATA_PATH_6)
    svm_function = train_svm(
        x,
        y,
        C=0.1,
        coef0=0.0,
        decision_function_shape="ovr",
        degree=3,
        gamma="auto",
        kernel="linear",
    )

    predictions = svm_function.predict(x)
    print(f"Training accuracy: {np.mean(predictions == y.flatten()) * 100}")

    x_test, y_test = read_test_data(DATA_PATH_7)
    predictions = svm_function.predict(x_test)
    print(f"Test accuracy: {np.mean(predictions == y_test.flatten()) * 100}")

    weights = svm_function.coef_[0]
    data_frame = pd.DataFrame({"vocabulary": vocabulary, "weights": weights})
    print(data_frame.sort_values(by="weights", ascending=False).head())


def main():
    plt.style.use("seaborn")
    part_1()
    part_2()
    part_3()
    part_4()
    plt.show()


if __name__ == "__main__":
    main()
